name: Check latest Volsync version

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  version_check:
    name: Get latest version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the latest version of Volsync
        run: |
          curl -s https://api.github.com/repos/backube/volsync/releases | jq -r '[.[] | select(.prerelease == false)][0] | .tag_name[1:]' > version
          echo "VOLSYNC_VERSION=$(cat version)" >> $GITHUB_ENV

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Version updated to: ${{ env.VOLSYNC_VERSION }}"
          tag: "v${{ env.VOLSYNC_VERSION }} --force"
